joint_names: ["tray_1_joint", "tray_2_joint", "tray_3_joint"]
at0: [[0.0, 0.0, 0.0]]
deliverup: [[0.35, 0.0, -1.725]]
displayup: [[0.15, 0.0, 1.05]]
deliverdown: [[-0.7, 0.0, -0.675]]
displaydown: [[-0.85, 0.0, 0.45]]
storetray: [[-1.15, 0.0, 1.40]]
upright: [[0.25, -1.57, 1.50]]
back: [[1.5, -1.57, 1.5]]
down1: [[-0.2, 0.0, 0.0]]
up1: [[0.2, 0.0, 0.0]]
down2: [[0.0, -0.2, 0.0]]
up2: [[0.0, 0.2, 0.0]]
down3: [[0.0, 0.0, -0.2]]
up3: [[0.0, 0.0, 0.2]]

to-back: [upright, back]
